# Vectorization of Logistic Regression
This notebook illustrates how to perform vectorization of common calculations encountered in logistic regression using NumPy.

In [43]:
import numpy as np

#### Training Dataset and Labels

In [44]:
np.random.seed(42)

X_T = np.random.rand(10,3)
X_T

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041]])

In [45]:
# Bias feature
dummy = np.ones(len(X_T))
dummy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
X_T = np.column_stack((dummy, X_T))
X_T

array([[1.        , 0.37454012, 0.95071431, 0.73199394],
       [1.        , 0.59865848, 0.15601864, 0.15599452],
       [1.        , 0.05808361, 0.86617615, 0.60111501],
       [1.        , 0.70807258, 0.02058449, 0.96990985],
       [1.        , 0.83244264, 0.21233911, 0.18182497],
       [1.        , 0.18340451, 0.30424224, 0.52475643],
       [1.        , 0.43194502, 0.29122914, 0.61185289],
       [1.        , 0.13949386, 0.29214465, 0.36636184],
       [1.        , 0.45606998, 0.78517596, 0.19967378],
       [1.        , 0.51423444, 0.59241457, 0.04645041]])

#### Generate labels for the samples.

In [47]:
labels = np.random.choice([0,1],(len(X_T)))
labels

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1])

#### Generate weights for initialization.

In [48]:
w = np.random.rand(len(X_T[0]))
w

array([0.80839735, 0.30461377, 0.09767211, 0.68423303])

# Logistic Regression

## W <sup>T</sup> X (or equivalently X<sup>T</sup>W) 

In [49]:
w_T_X = np.dot(w, X_T.T)
w_T_X

array([1.51620013, 1.11273224, 1.32199442, 1.68974089, 1.2071211 ,
       1.25303655, 1.38706867, 1.13010036, 1.16063574, 1.05468553])

## Sigmoid Activation

In [50]:
def sigmoid(w_T_X):
    return 1/ ( 1 - np.exp(-1. *w_T_X) )

h_theta = sigmoid(w_T_X)
h_theta

array([1.28130311, 1.48955766, 1.36351809, 1.22634284, 1.42664952,
       1.39984683, 1.33298942, 1.47710671, 1.45621231, 1.53445294])

## Gradient dW
Turns out that the gradients wrt the weights in logistic regression are identical to the gradients of linear regression except for the $h_{\theta}$.

### $h_{\theta}$ in linear regression was w<sup>T</sup>.X
<br>

### $h_{\theta}$ in logistic regression is ${\sigma}$ (w <sup> T</sup>.X)

In [51]:
dw = (h_theta - labels).dot(X_T)
dw

array([9.98797941, 4.41289043, 4.28475592, 4.5093801 ])

#### Weights before gradient update

In [52]:
w

array([0.80839735, 0.30461377, 0.09767211, 0.68423303])

#### Weights after gradient update

In [53]:
lr = 0.0001
w = w - lr * dw
w

array([0.80739855, 0.30417248, 0.09724364, 0.68378209])