These cheats are taken from various resources online.

# CREATING NUMPY ARRAYS

### Creating Integer Arrays

In [1]:
!pip3 install numpy upgrade
import numpy as np

print(np.__version__)

ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade
You should consider upgrading via the 'c:\users\being_aerys\appdata\local\programs\python\python36\python.exe -m pip install --upgrade pip' command.


1.16.2


In [2]:

sample_list = [1,2,3]
np.array(sample_list)

array([1, 2, 3])

In [3]:
sample_2D_list = [[1,2,3], [4,5,6], [7,8,9]]
sample_numpy_array = np.array(sample_2D_list)
sample_numpy_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating Arrays of Floating Points

In [4]:
sample_2D_list = [[1,2,3], [4,5,6], [7,8,9]]
sample_numpy_array = np.array(sample_2D_list, dtype = float)
sample_numpy_array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### Initializing NumPy Arrays with Placeholder Values

#### Initializing with All Zeroes

In [5]:
zeros_array = np.zeros((3,4)) # by defalt, all zeros are floating points.
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
zeros_array = np.zeros((3,4), dtype = int) # can initialize with integer zeros as well
zeros_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### Initializing with All Ones

In [7]:
ones_array = np.ones((2,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
ones_array = np.ones((2,4), dtype = int)
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#### Initialize with Values between a Range with a predefined Step

In [9]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

#### Initialize with evenly spaced values

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### Initialize with a constant array

In [11]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

#### Initialize an Identity Matrix

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Initialize with Random Values

#### Generate a random integer within a range [low, high)

In [14]:
np.random.randint(0,100)

89

#### Generate a random array of integers of a fixed shape within [low, high).

In [15]:
np.random.randint(0, 100, (2,3))

array([[48, 16, 65],
       [32, 41, 40]])

#### Generate a random floating point between [0,1)

In [16]:
np.random.rand()

0.9875029657585902

#### Generate a random array of floating points between [0,1)  in a given shape.

In [17]:
np.random.rand(5)

array([0.41719227, 0.95551983, 0.57538336, 0.21690716, 0.32178874])

In [18]:
np.random.rand(3,4)

array([[0.60956915, 0.64274052, 0.7339388 , 0.42773608],
       [0.6765415 , 0.10990447, 0.96816793, 0.27224524],
       [0.7140972 , 0.66707254, 0.85160173, 0.16219127]])

### Choose randomly from an array of values provided.

#### Choose a single value from a provided array.

In [19]:
dummy_array = np.array([1,2,3,4,5,6,7])
np.random.choice(dummy_array)

7

#### Choose a single value from an array with the associated probability of selection.

In [21]:
dummy_array = np.array([1,2,3,4,5])
dummy_prob = np.array([0.1,0.1,0.2,0.2,0.4])

np.random.choice(dummy_array, p = dummy_prob)

3

#### Choose values randomly to form a shape from a given array.

In [450]:
dummy_array = np.array([1,2,3,4,5,6,7])
np.random.choice(dummy_array, (3,4))

array([[4, 7, 1, 7],
       [1, 3, 1, 6],
       [6, 6, 1, 1]])

### Create an empty array.

In [451]:
np.empty((1,3))
# numpy.empty doesn't really create an empty array. It creates an array with an uninitialized data buffer -
# the elements of the array are whatever arbitrary garbage happened to be in that memory. This is not random.

array([[1., 1., 1.]])

# Functions in NumPy

# SAVING ON AND LOADING FROM DISK

### Save an array to a binary file in .npy format.

In [452]:
arr = np.array([1,2,3])
np.save("custom_filename", arr)

### Save multiple arrays into a single file in .npz format.

In [453]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([1,2,6])
arr_3 = np.array([1,4,6])
arr_4 = np.array([1,7,6])
np.savez("custom_file2", arr_1, arr_2, arr_3, arr_4)

# The arrays are stored as key-val pairs with names of the arrays as the default keys.

### Load a numpy array that was saved as a .npy file.

In [454]:
loaded_array = np.load("custom_filename.npy")
loaded_array

array([1, 2, 3])

### Load all arrays that we saved together into a .npz file.

In [455]:
loaded_arrays = np.load("custom_file2.npz")

# display the names of the arrays that were used when saving them into the .npz file
loaded_arrays.files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [456]:
# display one of the save arrays
loaded_arrays["arr_0"]

array([1, 2, 3])

### Load from a csv file.

In [457]:
np.genfromtxt("dummy_csv.csv")

array([9430875. , 9361062.5, 9375000. , ..., 8524625. , 8424500. ,
       8485500. ])

### Save an array into a csv file.

In [458]:
dummy_array = np.array([1,2,3,4,5,6,7])
np.savetxt("my_array.csv", dummy_array)

# INSPECTING NUMPY ARRAYS

In [459]:
arr = np.random.randint(0,100,(4,3,5))

#### Shape as a tuple

In [460]:
arr.shape

(4, 3, 5)

#### Length

In [461]:
len(arr)

4

#### Number of dimensions

In [462]:
arr.ndim

3

#### Number of total elements in the array

In [463]:
arr.size

60

#### Data type stored in an array

In [464]:
arr.dtype

dtype('int32')

#### Data type in string format

In [465]:
arr.dtype.name

'int32'

#### Conversion of array into another data type in-place

In [466]:
arr.astype(float)

array([[[36., 35., 20.,  1., 85.],
        [65.,  1., 61., 74., 59.],
        [93., 65., 38., 74., 62.]],

       [[23.,  8., 71., 18., 47.],
        [78., 60., 67., 86., 56.],
        [ 5., 13., 12., 94., 42.]],

       [[29., 34., 52., 87., 76.],
        [72., 88., 47., 22., 82.],
        [27., 82.,  7., 82., 12.]],

       [[ 0., 19., 54., 40., 18.],
        [77., 35.,  0., 82., 45.],
        [64., 42., 83.,  0., 80.]]])

# ARITHMETIC OPERATIONS OF NUMPY ARRAYS

In [467]:
arr1 = np.random.randint(0,10,(3))
arr2 = np.random.randint(0,10,(3))
arr3 = np.random.randint(0,10,(2))

In [468]:
arr1

array([0, 2, 0])

In [469]:
arr2

array([3, 1, 6])

In [470]:
arr3

array([2, 9])

Notice that arr1 and arr2 are of the same dimenions but arr3 is not.

#### Addition

In [471]:
arr2-arr1

array([ 3, -1,  6])

In [472]:
arr2-arr3

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

As seen above, trying to add two numpy arrays with different shape returns error.

#### Subtraction

In [473]:
arr1-arr2

array([-3,  1, -6])

In [474]:
np.subtract(arr1,arr2)

array([-3,  1, -6])

In [475]:
arr1-arr3

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

As seen above, trying to subtract two numpy arrays with different shape returns error.

#### Elementwise division between two same-shaped arrays

In [476]:
arr1 / arr2

array([0., 2., 0.])

In [477]:
np.divide(arr1, arr2)

array([0., 2., 0.])

#### Elementwise exponentiation, square root, sin, natural log

In [478]:
np.exp(arr1)

array([1.       , 7.3890561, 1.       ])

In [479]:
np.sqrt(arr2)

array([1.73205081, 1.        , 2.44948974])

In [480]:
np.sin(arr1)

array([0.        , 0.90929743, 0.        ])

In [481]:
np.log(arr2)

array([1.09861229, 0.        , 1.79175947])

#### Hadamard Product / Elementwise multiplication of two same-shaped arrays

In [482]:
arr1 * arr2

array([0, 2, 0])

In [483]:
np.multiply(arr1, arr2)

array([0, 2, 0])

#### Dot product between arrays
Dot product of two vectors requires them to be of the same lenghth.

In [484]:
np.dot(arr1, arr2)

2

In [485]:
arr1.dot(arr2)

2

In [486]:
np.dot(arr1, arr3)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

The dimensions of two vectors should be the same. Else results in an error as above.

#### Dot product in a multidimensional setting.
This can be achieved by using either np.dot() or np.matmul(). A dot product in a 2D setting amounts to matrix multiplication.  

In [487]:
weights = [[1,1,1,1],[2,2,2,2],[3,3,3,3]]
weights = np.array(weights)
weights

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [488]:
samples_as_rows = [[4,4,4,4],[5,5,5,5],[6,6,6,6]]
samples_as_rows = np.array(samples_as_rows)
samples_as_rows

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [489]:
np.matmul(weights,samples_as_rows.T)

array([[16, 20, 24],
       [32, 40, 48],
       [48, 60, 72]])

In [490]:
weights.dot(samples_as_rows.T)

array([[16, 20, 24],
       [32, 40, 48],
       [48, 60, 72]])

# COMPARISON

#### Elementwise comparison between corresponding elements of two arrays.

In [491]:
arr1 == arr2

array([False, False, False])

In [492]:
arr1 < arr2

array([ True, False,  True])

#### Elementwise comparison with a scalar.

In [493]:
arr1 > 2

array([False, False, False])

#### Comparing if two arrays are equal or not.

In [494]:
np.array_equal(arr1, arr2)

False

# AGGREGATE FUNCTIONS

#### Sum/ Max/ Min among all the elements in a numpy array.

In [495]:
arr1 = np.random.randint(0, 10, (3,4))
arr1

array([[9, 7, 9, 0],
       [9, 7, 8, 7],
       [3, 2, 1, 6]])

#### sum(arr1) sums across a column. DO NOT USE.

In [496]:
np.sum(arr1)

68

In [497]:
np.sum(arr1, axis = 0)

array([21, 16, 18, 13])

In [498]:
np.min(arr1)

0

In [499]:
np.min(arr1, axis = 1)

array([0, 7, 1])

#### min across a particular axis.

In [500]:
np.min(arr1, axis = 0) # 0 axis means columnwise

array([3, 2, 1, 0])

#### Cumulative sum of the elements.

In [501]:
# ACROSS A COLUMN
np.cumsum(arr1, axis = 0)

array([[ 9,  7,  9,  0],
       [18, 14, 17,  7],
       [21, 16, 18, 13]], dtype=int32)

In [502]:
# ACROSS A ROW
np.cumsum(arr1, axis = 1)

array([[ 9, 16, 25, 25],
       [ 9, 16, 24, 31],
       [ 3,  5,  6, 12]], dtype=int32)

In [503]:
np.mean(arr1)

5.666666666666667

In [504]:
np.mean(arr1, axis = 0) # axis 0 means across columns

array([7.        , 5.33333333, 6.        , 4.33333333])

In [505]:
np.median(arr1) # arr1.median() does not work.

7.0

In [506]:
np.median(arr1, axis = 1)

array([8. , 7.5, 2.5])

In [507]:
np.corrcoef(arr1)

array([[ 1.        ,  0.6723502 , -0.90299205],
       [ 0.6723502 ,  1.        , -0.32232919],
       [-0.90299205, -0.32232919,  1.        ]])

In [508]:
np.std(arr1)

3.1446603773522015

In [509]:
np.std(arr1, axis = 1)

array([3.69966215, 0.8291562 , 1.87082869])

# COPYING ARRAYS

In [510]:
arr1 = np.random.randint(0, 10, (3,4))
arr1

array([[8, 6, 1, 7],
       [2, 3, 3, 5],
       [3, 5, 2, 7]])

#### Creating a new view  (shallow copy) of the same array. View works as a shallow copy in numpy.
A view of a NumPy array is a shallow copy of the original array i.e. it references the same data buffer as the original, so changes to the original data affect the view data and vice versa. The view has its own facade which can be different from the original array, for example, shape. We can reshape a view to make vector calculations easier but this reshaping will not affect the shape of the original array. But if the values are changed, they are reflected in the original array.

In [511]:
new_view = arr1.view()
new_view

array([[8, 6, 1, 7],
       [2, 3, 3, 5],
       [3, 5, 2, 7]])

In [512]:
new_view -=1
new_view

array([[7, 5, 0, 6],
       [1, 2, 2, 4],
       [2, 4, 1, 6]])

In [513]:
arr1

array([[7, 5, 0, 6],
       [1, 2, 2, 4],
       [2, 4, 1, 6]])

As seen above, changes made to the view affected the original array that was used to create the view indicating that both of them share the same memory.

#### Every numpy array object has an attribute "base" that returns None if the array owns the data. Else, the base attribute returns the original array referenced.

In [514]:
print(arr1.base)

None


In [515]:
print(new_view.base)

[[7 5 0 6]
 [1 2 2 4]
 [2 4 1 6]]


#### Creating a deep copy of the array. copy() method works as deepcopy in numpy.
Making changes to this copy will not affect the original array.

In [516]:
new_copy = np.copy(arr1)
new_copy

array([[7, 5, 0, 6],
       [1, 2, 2, 4],
       [2, 4, 1, 6]])

In [517]:
print(new_copy.base)

None


In [518]:
new_copy -= 1
new_copy

array([[ 6,  4, -1,  5],
       [ 0,  1,  1,  3],
       [ 1,  3,  0,  5]])

In [519]:
arr1

array([[7, 5, 0, 6],
       [1, 2, 2, 4],
       [2, 4, 1, 6]])

In [520]:
As seen, the original array is unaffected.

SyntaxError: invalid syntax (<ipython-input-520-b2c65ae48ea0>, line 1)

#### Creating a deepcopy of an array. (2nd method)

In [521]:
deepcopy_arr1 = arr1.copy()
deepcopy_arr1

array([[7, 5, 0, 6],
       [1, 2, 2, 4],
       [2, 4, 1, 6]])

In [522]:
deepcopy_arr1 -= 1
deepcopy_arr1

array([[ 6,  4, -1,  5],
       [ 0,  1,  1,  3],
       [ 1,  3,  0,  5]])

In [523]:
arr1

array([[7, 5, 0, 6],
       [1, 2, 2, 4],
       [2, 4, 1, 6]])

As seen, the original array is unaffected.

In [524]:
print(deepcopy_arr1.base)

None


# SORTING ARRAYS

### One-dimensional sorting

In [525]:
arr = np.array([1,2, 4, 7, 2,1 ,2,3,4,5])
arr

array([1, 2, 4, 7, 2, 1, 2, 3, 4, 5])

#### In-place sorting

In [526]:
# In-place sorting
arr.sort()
arr

array([1, 1, 2, 2, 2, 3, 4, 4, 5, 7])

#### Out-of-place sorting

In [527]:
# New sorted array
arr = np.array([1,2, 4, 7, 2,1 ,2,3,4,5])
new_arr = np.sort(arr)
new_arr

array([1, 1, 2, 2, 2, 3, 4, 4, 5, 7])

### Multidimensional sorting

#### In-place

In [528]:
raw = [[1,5, 34,27, 22,24 ,72,34,41,5],[0,12, 45, 67, 2,1 ,2,3,1,5],[1,32, 4, 22, 2,166,2,3,4,2]]
arr = np.array(raw)
arr

array([[  1,   5,  34,  27,  22,  24,  72,  34,  41,   5],
       [  0,  12,  45,  67,   2,   1,   2,   3,   1,   5],
       [  1,  32,   4,  22,   2, 166,   2,   3,   4,   2]])

In [529]:
arr.sort(axis = 0) # axis = 0 means column-wise
arr

array([[  0,   5,   4,  22,   2,   1,   2,   3,   1,   2],
       [  1,  12,  34,  27,   2,  24,   2,   3,   4,   5],
       [  1,  32,  45,  67,  22, 166,  72,  34,  41,   5]])

In [530]:
raw = [[1,0, 4,27, 2,24 ,72,34,41,5],[1,2, 4, 67, 2,1 ,2,3,1,5],[1,2, 4, 22, 2,1 ,2,3,4,2]]
arr = np.array(raw)
arr

array([[ 1,  0,  4, 27,  2, 24, 72, 34, 41,  5],
       [ 1,  2,  4, 67,  2,  1,  2,  3,  1,  5],
       [ 1,  2,  4, 22,  2,  1,  2,  3,  4,  2]])

In [531]:
arr.sort(axis = 1) # axis = 1 means row-wise
arr

array([[ 0,  1,  2,  4,  5, 24, 27, 34, 41, 72],
       [ 1,  1,  1,  2,  2,  2,  3,  4,  5, 67],
       [ 1,  1,  2,  2,  2,  2,  3,  4,  4, 22]])

#### Out-of-place

In [532]:
raw = [[1,0, 4,27, 2,24 ,72,34,41,5],[1,2, 4, 67, 2,1 ,2,3,1,5],[1,2, 4, 22, 2,1 ,2,3,4,2]]
arr = np.array(raw)
arr

array([[ 1,  0,  4, 27,  2, 24, 72, 34, 41,  5],
       [ 1,  2,  4, 67,  2,  1,  2,  3,  1,  5],
       [ 1,  2,  4, 22,  2,  1,  2,  3,  4,  2]])

In [533]:
new_arr = np.sort(arr, axis = 0)
new_arr

array([[ 1,  0,  4, 22,  2,  1,  2,  3,  1,  2],
       [ 1,  2,  4, 27,  2,  1,  2,  3,  4,  5],
       [ 1,  2,  4, 67,  2, 24, 72, 34, 41,  5]])

In [534]:
raw = [[1,0, 4,27, 2,24 ,72,34,41,5],[1,2, 4, 67, 2,1 ,2,3,1,5],[1,2, 4, 22, 2,1 ,2,3,4,2]]
arr = np.array(raw)
arr

array([[ 1,  0,  4, 27,  2, 24, 72, 34, 41,  5],
       [ 1,  2,  4, 67,  2,  1,  2,  3,  1,  5],
       [ 1,  2,  4, 22,  2,  1,  2,  3,  4,  2]])

In [535]:
new_arr = np.sort(arr, axis = 1)
new_arr

array([[ 0,  1,  2,  4,  5, 24, 27, 34, 41, 72],
       [ 1,  1,  1,  2,  2,  2,  3,  4,  5, 67],
       [ 1,  1,  2,  2,  2,  2,  3,  4,  4, 22]])

# SUBSETTING, SLICING, INDEXING

In [536]:
a = np.array([1,2,3])
a[1] # selects the 1th index element of the first dimension

2

In [537]:
a = np.array([[1,2,3],[4,5,6]])
a[1]

array([4, 5, 6])

In [538]:
a = np.array([[1,2,3],[4,5,6]])
a[1][2]

6

In [539]:
a = np.array([[1,2,3],[4,5,6], [7,8,9],[10,11,12]])
a[2:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [540]:
a[2][1:]

array([8, 9])

In [541]:
a = np.array([[1,2,3],[4,5,6], [7,8,9],[10,11,12]])
a[1:]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [542]:
a[1:, 1:] # All rows from the 2nd row, all columns from the second column.
          # Note : a[1:][1:] does not gives [1:] of the result of a[1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [543]:
a = np.array([[[1,2,3],[4,5,6], [7,8,9],[10,11,12]],[[1,2,3],[4,5,6], [7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [544]:
a[1:,1:, 1:]

array([[[ 5,  6],
        [ 8,  9],
        [11, 12]]])

#### Boolean Indexing 1D array
Get the indices of the elements that satisfy a given condition.

In [545]:
a = np.array([[1,2,3],[4,5,6]])
indices = a%2 == 0 # here a%2 == 0 is the condition to check.
indices

array([[False,  True, False],
       [ True, False,  True]])

In [546]:
a[indices] # retrieves all the elements that have a corresponding True in the indices array.

array([2, 4, 6])

#### Boolean Indexing 2D array

In [547]:
a = np.array([[[1,2,3],[4,5,6], [7,8,9],[10,11,12]],[[1,2,3],[4,5,6], [7,8,9],[10,11,12]]])
indices = a > 5
indices

array([[[False, False, False],
        [False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[False, False, False],
        [False, False,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [548]:
a[indices]

array([ 6,  7,  8,  9, 10, 11, 12,  6,  7,  8,  9, 10, 11, 12])

# ARRAY MANIPULATION

### Transposing an array

#### 1D

In [549]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [550]:
a.T

array([1, 2, 3, 4, 5])

#### 2D

In [551]:
a = np.array([[1,2,3,4,5],[31,3,2,8,90]])
a

array([[ 1,  2,  3,  4,  5],
       [31,  3,  2,  8, 90]])

In [552]:
a.T

array([[ 1, 31],
       [ 2,  3],
       [ 3,  2],
       [ 4,  8],
       [ 5, 90]])

#### 3D

In [553]:
a = np.array([[[1,2,3],[4,5,6], [7,8,9],[10,11,12]],[[11,12,13],[14,15,16], [17,18,19],[110,111,112]]])
a

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 10,  11,  12]],

       [[ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19],
        [110, 111, 112]]])

In [554]:
a.shape

(2, 4, 3)

In [555]:
b = a.transpose((0,2,1)) # switch axes 1 and 2, leave the 0 axis as it is.
b

array([[[  1,   4,   7,  10],
        [  2,   5,   8,  11],
        [  3,   6,   9,  12]],

       [[ 11,  14,  17, 110],
        [ 12,  15,  18, 111],
        [ 13,  16,  19, 112]]])

### Change array shape.

In [556]:
a = np.array([[1,2,3,4,5],[31,3,2,8,90]])
a

array([[ 1,  2,  3,  4,  5],
       [31,  3,  2,  8, 90]])

#### Flatten the array out of place.

In [557]:
flat = a.ravel()
flat

array([ 1,  2,  3,  4,  5, 31,  3,  2,  8, 90])

#### Reshape the array.

In [558]:
a.shape

(2, 5)

#### In-place using reshape()

Directly reshaping is equivalent to flattening the array and filling in the array in sequence.<br>
As such, it might not produce intended result if not checked.

In [559]:
a.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5, 31],
       [ 3,  2],
       [ 8, 90]])

### Append new elements to an array.
Append operation creates a new copy of the original array and appends the new elements to this new array.

#### 1D

In [560]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [561]:
new_a = np.append(a,4)
new_a

array([1, 2, 3, 4])

#### 2D

#### Appending a new row.

In [562]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [563]:
new_a = np.append(a, np.array([[11,12,13,14,15]]), axis = 0) # notice that we have passed a 2D array. i.e.., [[XXXXX]]
new_a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### Appending a new column.

In [564]:
col_transposed = np.array([[20,30]])
col_transposed


array([[20, 30]])

In [565]:
new_a = np.append(a, col, axis = 1) # notice that we have passed a 2D array. i.e.., [[XXXXX]]
new_a

array([[ 1,  2,  3,  4,  5, 20],
       [ 6,  7,  8,  9, 10, 30]])

### Insert new elements at a particular index.
Creates a new copy of the array where the new element is inserted at a desired position.

#### 1D

In [566]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [567]:
new = np.insert(a, 2, 5)
new

array([1, 2, 5, 3])

#### 2D

#### Insert as a new row.

In [568]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [569]:
new = np.insert(a, 0, np.array([11,12,13,14,15]), axis = 0)
new

array([[11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Insert as a new column.

In [570]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [571]:
col_transposed = np.array([[20,30]])
col_transposed

array([[20, 30]])

In [572]:
new = np.insert(a, 0, col_transposed, axis = 1)
new

array([[20,  1,  2,  3,  4,  5],
       [30,  6,  7,  8,  9, 10]])

### Delete elements.

#### 1D

In [573]:
a = np.array([1,2,3,4,5])
new = np.delete(a, 1) # delete the element at position 1
new

array([1, 3, 4, 5])

#### 2D

In [574]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,14,14,15]])
new = np.delete(a, 1, axis = 0) # delete the row at position 0
new

array([[ 1,  2,  3,  4,  5],
       [11, 12, 14, 14, 15]])

In [575]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,14,14,15]])
new = np.delete(a, 1, axis = 1) # delete the column at position 1
new

array([[ 1,  3,  4,  5],
       [ 6,  8,  9, 10],
       [11, 14, 14, 15]])

### Combining Arrays

#### CONCATENATION

#### 1D

In [576]:
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.concatenate((a,b), axis = 0)
result

array([1, 2, 3, 4, 5, 6])

#### 2D

In [577]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
result = np.concatenate((a,b), axis = 0)
result

array([[1, 2, 3],
       [4, 5, 6]])

In [578]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
result = np.concatenate((a,b), axis = 1)
result

array([[1, 2, 3, 4, 5, 6]])

#### Vertical and Horizontal Stacking

#### 1D

In [579]:
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.vstack((a,b))
result

array([[1, 2, 3],
       [4, 5, 6]])

In [580]:
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.hstack((a,b))
result

array([1, 2, 3, 4, 5, 6])

#### 2D

In [581]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
result = np.vstack((a,b))
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [582]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[10,11,12]])
result = np.hstack((a,b))
result

array([[ 1,  2,  3,  4,  5,  6],
       [ 4,  5,  6, 10, 11, 12]])

#### 3D

In [583]:
a = np.array([[[1,2,3],[4,5,6], [7,8,9]],[[11,12,13],[14,15,16], [17,18,19]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [584]:
b = np.array([[[1,2,3],[4,5,6], [7,8,9]],[[11,12,13],[14,15,16], [17,18,19]]])

In [585]:
np.vstack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [586]:
np.hstack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

#### Column Stack
Take a sequence of 1-D arrays and stack them as columns to make a single 2-D array.<br>
2-D arrays are stacked as-is, just like with hstack.

In [587]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [588]:
np.column_stack((a,b)) 

array([[1, 4],
       [2, 5],
       [3, 6]])

### Splitting Arrays

#### hsplit(arr, n)
Split an array into n sub-arrays splitting blocks of columns.

In [589]:
a = np.array([[1,2,3,3],[4,5,6,6], [7,8,9,9],[11,12,13,13],[14,15,16,16], [17,18,19,19]])
a

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  6],
       [ 7,  8,  9,  9],
       [11, 12, 13, 13],
       [14, 15, 16, 16],
       [17, 18, 19, 19]])

In [590]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [11, 12],
        [14, 15],
        [17, 18]]), array([[ 3,  3],
        [ 6,  6],
        [ 9,  9],
        [13, 13],
        [16, 16],
        [19, 19]])]

#### vsplit(arr, n)
Split an array into n sub-arrays splitting blocks of rows.

In [591]:
a = np.array([[1,2,3,3],[4,5,6,6], [7,8,9,9],[11,12,13,13],[14,15,16,16], [17,18,19,19]])
a

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  6],
       [ 7,  8,  9,  9],
       [11, 12, 13, 13],
       [14, 15, 16, 16],
       [17, 18, 19, 19]])

In [592]:
np.vsplit(a,2)

[array([[1, 2, 3, 3],
        [4, 5, 6, 6],
        [7, 8, 9, 9]]), array([[11, 12, 13, 13],
        [14, 15, 16, 16],
        [17, 18, 19, 19]])]